# Use Node.js LTS version
FROM node:14-alpine

# Set working directory
WORKDIR /src

# Copy package.json and package-lock.json separately to leverage Docker cache
COPY app/package*.json ./

# Install dependencies
RUN npm install --quiet

# Copy the rest of the application
COPY app/ .

# Expose port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
